
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'COMMA DOLLAR LBRACE LPAREN LSQUABRAC NUMBER RBRACE RPAREN RSQUABRAC SEMICOLON WORDfile : blocksblocks : blocks block\n| blockblock : dictionary\n| listblock\n| statement\n| hexEdge_items\n| coordlists\n| emptylistblock : WORD LPAREN blocks RPAREN SEMICOLONcoordlists : coordlists coodlist\n| coodlist\n\ncoodlist : LPAREN anylist RPAREN\nhexEdge_items : hexEdge_items hexEdge_item\n| hexEdge_item\nhexEdge_item : hex_item \n| edge_itemhex_item : WORD LPAREN NUMBER NUMBER NUMBER NUMBER NUMBER NUMBER NUMBER NUMBER RPAREN LPAREN NUMBER NUMBER NUMBER RPAREN word gradlistedge_item : WORD number number gradlistgradlist : coodlist \n| LPAREN coordlists RPAREN\ndictionary : WORD LBRACE blocks RBRACEstatement : WORD anylist SEMICOLONanylist : anylist sitem\n| sitem\nsitem : word\n    | number\n    | dimension\n    | vector\n    | empty\n\nword : WORD\n\nnumber : NUMBER\n\nvector : LPAREN NUMBER NUMBER NUMBER RPAREN\n\ndimension : LSQUABRAC NUMBER NUMBER NUMBER NUMBER NUMBER NUMBER NUMBER RSQUABRAC \nempty :'
    
_lr_action_items = {'WORD':([0,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,19,20,21,22,23,24,25,26,27,28,29,30,33,34,37,38,40,41,45,47,50,51,52,56,58,64,65,66,75,81,83,],[10,10,-3,-4,-5,-6,18,-8,-9,20,20,-15,-12,-16,-17,-2,-14,-11,-31,10,10,20,-32,-26,-27,-25,-28,-29,-30,20,-27,10,10,-23,-24,-13,-22,-19,-20,20,-10,20,-33,-32,-21,-34,20,-18,]),'LPAREN':([0,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,33,34,37,38,40,41,42,45,47,50,51,52,56,58,59,64,65,66,75,76,82,83,],[11,11,-3,-4,-5,-6,-7,11,-9,22,32,-15,-12,-16,-17,-2,-14,35,-11,-31,11,11,32,-32,-26,-27,-25,-28,-29,-30,32,-27,11,11,-23,-24,52,-13,-22,-19,-20,58,-10,32,11,-33,-32,-21,-34,77,52,-18,]),'$end':([0,1,2,3,4,5,6,7,8,9,12,13,14,15,16,17,19,40,45,47,50,51,56,66,83,],[-35,0,-1,-3,-4,-5,-6,-7,-8,-9,-15,-12,-16,-17,-2,-14,-11,-23,-13,-22,-19,-20,-10,-21,-18,]),'RBRACE':([3,4,5,6,7,8,9,12,13,14,15,16,17,19,21,37,40,45,47,50,51,56,66,83,],[-3,-4,-5,-6,-7,-8,-9,-15,-12,-16,-17,-2,-14,-11,-35,47,-23,-13,-22,-19,-20,-10,-21,-18,]),'RPAREN':([3,4,5,6,7,8,9,11,12,13,14,15,16,17,19,20,22,24,25,27,28,29,30,33,34,38,40,41,45,47,50,51,52,56,57,58,59,61,64,65,66,74,75,80,83,],[-3,-4,-5,-6,-7,-8,-9,-35,-15,-12,-16,-17,-2,-14,-11,-31,-35,-32,-26,-25,-28,-29,-30,45,-27,48,-23,-24,-13,-22,-19,-20,-35,-10,64,-35,66,64,-33,-32,-21,76,-34,81,-18,]),'LBRACE':([10,],[21,]),'NUMBER':([10,11,18,20,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,39,41,43,44,46,49,52,53,54,55,57,58,60,62,63,64,65,67,68,69,70,71,72,75,77,78,79,],[24,24,24,-31,39,24,-32,-26,24,-25,-28,-29,-30,43,44,24,-27,46,24,49,-24,53,54,55,57,24,60,61,62,63,65,67,63,68,-33,54,69,70,71,72,73,74,-34,78,79,80,]),'LSQUABRAC':([10,11,20,23,24,25,26,27,28,29,30,33,34,41,52,58,64,65,75,],[31,31,-31,31,-32,-26,-27,-25,-28,-29,-30,31,-27,-24,31,31,-33,-32,-34,]),'SEMICOLON':([10,20,23,24,25,26,27,28,29,30,34,41,48,64,75,],[-35,-31,40,-32,-26,-27,-25,-28,-29,-30,-27,-24,56,-33,-34,]),'RSQUABRAC':([73,],[75,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'file':([0,],[1,]),'blocks':([0,21,22,],[2,37,38,]),'block':([0,2,21,22,37,38,],[3,16,3,3,16,16,]),'dictionary':([0,2,21,22,37,38,],[4,4,4,4,4,4,]),'listblock':([0,2,21,22,37,38,],[5,5,5,5,5,5,]),'statement':([0,2,21,22,37,38,],[6,6,6,6,6,6,]),'hexEdge_items':([0,2,21,22,37,38,],[7,7,7,7,7,7,]),'coordlists':([0,2,21,22,37,38,52,],[8,8,8,8,8,8,59,]),'empty':([0,2,10,11,21,22,23,33,37,38,52,58,],[9,9,30,30,9,9,30,30,9,9,30,30,]),'hexEdge_item':([0,2,7,21,22,37,38,],[12,12,17,12,12,12,12,]),'coodlist':([0,2,8,21,22,37,38,42,52,59,82,],[13,13,19,13,13,13,13,51,13,19,51,]),'hex_item':([0,2,7,21,22,37,38,],[14,14,14,14,14,14,14,]),'edge_item':([0,2,7,21,22,37,38,],[15,15,15,15,15,15,15,]),'anylist':([10,11,52,58,],[23,33,33,33,]),'word':([10,11,23,33,52,58,81,],[25,25,25,25,25,25,82,]),'number':([10,11,18,23,26,33,36,52,58,],[26,34,36,34,42,34,42,34,34,]),'sitem':([10,11,23,33,52,58,],[27,27,41,41,27,27,]),'dimension':([10,11,23,33,52,58,],[28,28,28,28,28,28,]),'vector':([10,11,23,33,52,58,],[29,29,29,29,29,29,]),'gradlist':([42,82,],[50,83,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> file","S'",1,None,None,None),
  ('file -> blocks','file',1,'p_file','Parser.py',192),
  ('blocks -> blocks block','blocks',2,'p_blocks','Parser.py',204),
  ('blocks -> block','blocks',1,'p_blocks','Parser.py',205),
  ('block -> dictionary','block',1,'p_block','Parser.py',242),
  ('block -> listblock','block',1,'p_block','Parser.py',243),
  ('block -> statement','block',1,'p_block','Parser.py',244),
  ('block -> hexEdge_items','block',1,'p_block','Parser.py',245),
  ('block -> coordlists','block',1,'p_block','Parser.py',246),
  ('block -> empty','block',1,'p_block','Parser.py',247),
  ('listblock -> WORD LPAREN blocks RPAREN SEMICOLON','listblock',5,'p_listblock','Parser.py',251),
  ('coordlists -> coordlists coodlist','coordlists',2,'p_coodlists','Parser.py',269),
  ('coordlists -> coodlist','coordlists',1,'p_coodlists','Parser.py',270),
  ('coodlist -> LPAREN anylist RPAREN','coodlist',3,'p_coordlist','Parser.py',279),
  ('hexEdge_items -> hexEdge_items hexEdge_item','hexEdge_items',2,'p_hexEdge_items','Parser.py',284),
  ('hexEdge_items -> hexEdge_item','hexEdge_items',1,'p_hexEdge_items','Parser.py',285),
  ('hexEdge_item -> hex_item','hexEdge_item',1,'p_hexEdge_item','Parser.py',293),
  ('hexEdge_item -> edge_item','hexEdge_item',1,'p_hexEdge_item','Parser.py',294),
  ('hex_item -> WORD LPAREN NUMBER NUMBER NUMBER NUMBER NUMBER NUMBER NUMBER NUMBER RPAREN LPAREN NUMBER NUMBER NUMBER RPAREN word gradlist','hex_item',18,'p_hex_item','Parser.py',298),
  ('edge_item -> WORD number number gradlist','edge_item',4,'p_edge_item','Parser.py',321),
  ('gradlist -> coodlist','gradlist',1,'p_gradelist','Parser.py',325),
  ('gradlist -> LPAREN coordlists RPAREN','gradlist',3,'p_gradelist','Parser.py',326),
  ('dictionary -> WORD LBRACE blocks RBRACE','dictionary',4,'p_dictionary','Parser.py',335),
  ('statement -> WORD anylist SEMICOLON','statement',3,'p_statement','Parser.py',350),
  ('anylist -> anylist sitem','anylist',2,'p_anylist','Parser.py',357),
  ('anylist -> sitem','anylist',1,'p_anylist','Parser.py',358),
  ('sitem -> word','sitem',1,'p_sitem','Parser.py',367),
  ('sitem -> number','sitem',1,'p_sitem','Parser.py',368),
  ('sitem -> dimension','sitem',1,'p_sitem','Parser.py',369),
  ('sitem -> vector','sitem',1,'p_sitem','Parser.py',370),
  ('sitem -> empty','sitem',1,'p_sitem','Parser.py',371),
  ('word -> WORD','word',1,'p_word','Parser.py',377),
  ('number -> NUMBER','number',1,'p_number','Parser.py',383),
  ('vector -> LPAREN NUMBER NUMBER NUMBER RPAREN','vector',5,'p_vector','Parser.py',392),
  ('dimension -> LSQUABRAC NUMBER NUMBER NUMBER NUMBER NUMBER NUMBER NUMBER RSQUABRAC','dimension',9,'p_dimension','Parser.py',398),
  ('empty -> <empty>','empty',0,'p_empty','Parser.py',404),
]
